language: python

python:
  - "2.7"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/libspimage
    - $HOME/spsim
    - $HOME/local

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - couchbase-precise
    packages:
      - libpng-dev
      - libtiff4-dev
      - libfftw3-dev
      - libhdf5-serial-dev
      - cmake
      - gsl-bin
      - libgsl0-dev

before_install:
# Install libspimage
  - cat /usr/include/H5public.h
  - cd $HOME
  - if [ ! -d "$HOME/libspimage/.git" ]; then git clone https://github.com/FilipeMaia/libspimage; else echo 'Using libspimage from cached directory'; fi
  - mkdir -p libspimage/build && cd libspimage/build
  - git pull
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_CUDA=OFF -DCMAKE_C_FLAGS=\"-DH5_USE_18_API=1\" -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
  - make -j 2
  - make install
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib
# Install spsim
  - cd $HOME
  - if [ ! -d "$HOME/spsim/.git" ]; then git clone https://github.com/FilipeMaia/spsim; else echo 'Using spsim from cached directory'; fi
  - mkdir -p spsim/build && cd spsim/build
  - git pull
  - cmake -DUSE_CUDA=OFF -DUSE_NFFT=OFF -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
  - make -j 2
  - make install
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib
# szip???
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: python -m unittest -v condor.tests.test_all
